include(../plugins/Plugins.cmake)

MACRO(DFHACK_SCRIPTS)
  PARSE_ARGUMENTS(SCRIPT
    "SUBDIRECTORY"
    "SOME_OPT"
    ${ARGN}
  )
  CAR(SCRIPT_SUBDIRECTORY ${SCRIPT_SUBDIRECTORY})
  install(FILES ${SCRIPT_DEFAULT_ARGS}
    DESTINATION ${DFHACK_DATA_DESTINATION}/scripts/${SCRIPT_SUBDIRECTORY})
ENDMACRO()
